/*
 *  builtin_argtypes.h
 *  Daruma Basic
 *
 *  Created by Toshi Nagata on 2015/12/17.
 *  Copyright 2015 Toshi Nagata.  All rights reserved.
 *
 */

#ifndef __builtin_argtypes_h__
#define __builtin_argtypes_h__

#define SIGTYPE const u_int8_t *

#define BS_ARG_XXXX ""
#define BS_ARG_IXXX "\x01"
#define BS_ARG_FXXX "\x02"
#define BS_ARG_SXXX "\x03"
#define BS_ARG_IIXX "\x05"
#define BS_ARG_FIXX "\x06"
#define BS_ARG_SIXX "\x07"
#define BS_ARG_IFXX "\x09"
#define BS_ARG_FFXX "\x0A"
#define BS_ARG_SFXX "\x0B"
#define BS_ARG_ISXX "\x0D"
#define BS_ARG_FSXX "\x0E"
#define BS_ARG_SSXX "\x0F"
#define BS_ARG_IIIX "\x15"
#define BS_ARG_FIIX "\x16"
#define BS_ARG_SIIX "\x17"
#define BS_ARG_IFIX "\x19"
#define BS_ARG_FFIX "\x1A"
#define BS_ARG_SFIX "\x1B"
#define BS_ARG_ISIX "\x1D"
#define BS_ARG_FSIX "\x1E"
#define BS_ARG_SSIX "\x1F"
#define BS_ARG_IIFX "\x25"
#define BS_ARG_FIFX "\x26"
#define BS_ARG_SIFX "\x27"
#define BS_ARG_IFFX "\x29"
#define BS_ARG_FFFX "\x2A"
#define BS_ARG_SFFX "\x2B"
#define BS_ARG_ISFX "\x2D"
#define BS_ARG_FSFX "\x2E"
#define BS_ARG_SSFX "\x2F"
#define BS_ARG_IISX "\x35"
#define BS_ARG_FISX "\x36"
#define BS_ARG_SISX "\x37"
#define BS_ARG_IFSX "\x39"
#define BS_ARG_FFSX "\x3A"
#define BS_ARG_SFSX "\x3B"
#define BS_ARG_ISSX "\x3D"
#define BS_ARG_FSSX "\x3E"
#define BS_ARG_SSSX "\x3F"
#define BS_ARG_IIII "\x55"
#define BS_ARG_FIII "\x56"
#define BS_ARG_SIII "\x57"
#define BS_ARG_IFII "\x59"
#define BS_ARG_FFII "\x5A"
#define BS_ARG_SFII "\x5B"
#define BS_ARG_ISII "\x5D"
#define BS_ARG_FSII "\x5E"
#define BS_ARG_SSII "\x5F"
#define BS_ARG_IIFI "\x65"
#define BS_ARG_FIFI "\x66"
#define BS_ARG_SIFI "\x67"
#define BS_ARG_IFFI "\x69"
#define BS_ARG_FFFI "\x6A"
#define BS_ARG_SFFI "\x6B"
#define BS_ARG_ISFI "\x6D"
#define BS_ARG_FSFI "\x6E"
#define BS_ARG_SSFI "\x6F"
#define BS_ARG_IISI "\x75"
#define BS_ARG_FISI "\x76"
#define BS_ARG_SISI "\x77"
#define BS_ARG_IFSI "\x79"
#define BS_ARG_FFSI "\x7A"
#define BS_ARG_SFSI "\x7B"
#define BS_ARG_ISSI "\x7D"
#define BS_ARG_FSSI "\x7E"
#define BS_ARG_SSSI "\x7F"
#define BS_ARG_IIIF "\x95"
#define BS_ARG_FIIF "\x96"
#define BS_ARG_SIIF "\x97"
#define BS_ARG_IFIF "\x99"
#define BS_ARG_FFIF "\x9A"
#define BS_ARG_SFIF "\x9B"
#define BS_ARG_ISIF "\x9D"
#define BS_ARG_FSIF "\x9E"
#define BS_ARG_SSIF "\x9F"
#define BS_ARG_IIFF "\xA5"
#define BS_ARG_FIFF "\xA6"
#define BS_ARG_SIFF "\xA7"
#define BS_ARG_IFFF "\xA9"
#define BS_ARG_FFFF "\xAA"
#define BS_ARG_SFFF "\xAB"
#define BS_ARG_ISFF "\xAD"
#define BS_ARG_FSFF "\xAE"
#define BS_ARG_SSFF "\xAF"
#define BS_ARG_IISF "\xB5"
#define BS_ARG_FISF "\xB6"
#define BS_ARG_SISF "\xB7"
#define BS_ARG_IFSF "\xB9"
#define BS_ARG_FFSF "\xBA"
#define BS_ARG_SFSF "\xBB"
#define BS_ARG_ISSF "\xBD"
#define BS_ARG_FSSF "\xBE"
#define BS_ARG_SSSF "\xBF"
#define BS_ARG_IIIS "\xD5"
#define BS_ARG_FIIS "\xD6"
#define BS_ARG_SIIS "\xD7"
#define BS_ARG_IFIS "\xD9"
#define BS_ARG_FFIS "\xDA"
#define BS_ARG_SFIS "\xDB"
#define BS_ARG_ISIS "\xDD"
#define BS_ARG_FSIS "\xDE"
#define BS_ARG_SSIS "\xDF"
#define BS_ARG_IIFS "\xE5"
#define BS_ARG_FIFS "\xE6"
#define BS_ARG_SIFS "\xE7"
#define BS_ARG_IFFS "\xE9"
#define BS_ARG_FFFS "\xEA"
#define BS_ARG_SFFS "\xEB"
#define BS_ARG_ISFS "\xED"
#define BS_ARG_FSFS "\xEE"
#define BS_ARG_SSFS "\xEF"
#define BS_ARG_IISS "\xF5"
#define BS_ARG_FISS "\xF6"
#define BS_ARG_SISS "\xF7"
#define BS_ARG_IFSS "\xF9"
#define BS_ARG_FFSS "\xFA"
#define BS_ARG_SFSS "\xFB"
#define BS_ARG_ISSS "\xFD"
#define BS_ARG_FSSS "\xFE"
#define BS_ARG_SSSS "\xFF"

#endif /* __builtin_argtypes_h__ */
