/*
 *  transmessage.h
 *  Daruma Basic
 *
 *  Created by Toshi Nagata on 16/02/15.
 *  Copyright 2016 Toshi Nagata. All rights reserved.
 *
 */

#ifndef __TRANSMESSAGE_H__
#define __TRANSMESSAGE_H__

#if 0
#pragma mark ====== Internationalization ======
#endif

const char *bs_translate_msg(const char *msg);
const char *bs_get_translated_msg(int msgid);

#define YY_(msg) bs_translate_msg(msg)
#define MSG_(msgid) bs_get_translated_msg(msgid)

enum {
	BS_M_ONLY_ONE_DO_COND,
	BS_M_UNDEF_SYMBOL,
	BS_M_DIM_DECL,
	BS_M_BAD_CONST_EXPR,
	BS_M_UNKNOWN_UNARY,
	BS_M_NUMBER_EXPECTED,
	BS_M_TYPE_MISMATCH,
	BS_M_ILLEGAL_OP_STR,
	BS_M_UNKNOWN_BINARY,
	BS_M_MUST_BE_INTEGER,
	BS_M_UNKNOWN_INT_BINARY,
	BS_M_INTERNAL_ERROR_1,
	BS_M_CANNOT_CONVERT_FLT,
	BS_M_CANNOT_CONVERT_INT,
	BS_M_CANNOT_CONVERT_STR,
	BS_M_UNKNOWN_TYPE_STORE,
	BS_M_UNKNOWN_TYPE_LOAD,
	BS_M_NOT_INSIDE_IF,
	BS_M_NOT_INSIDE_LOOP,
	BS_M_ILLEGAL_DIM,
	BS_M_DIM_NO_MATCH,
	BS_M_INDEX,
	BS_M_INDICES,
	BS_M_TOO_MANY_LOOPS,
	BS_M_TOO_MANY_LOCALS,
	BS_M_BREAK_OUTSIDE_LOOP,
	BS_M_CONTINUE_OUTSIDE_LOOP,
	BS_M_COND_NUMERIC,
	BS_M_DUPLICATE_LABEL,
	BS_M_JUMP_INTO_LOOP_OR_FUNC,
	BS_M_JUMP_INTO_OUTOF_FUNC,
	BS_M_JUMP_INTO_FORLOOP,
	BS_M_LINES_FMT,
	BS_M_LINE_FMT,
	BS_M_ETC,
	BS_M_LABEL_NOT_DEFINED,
	BS_M_PROCFUNC_NOT_DEFINED,
	BS_M_PROC,
	BS_M_FUNC,
	BS_M_PROC_NOT_FUNC,
	BS_M_FUNC_NOT_PROC,
	BS_M_OUT_OF_MEMORY_ARG,
	BS_M_ARG_CANNOT_COERCE,
	BS_M_BAD_DIM_ARG,
	BS_M_TOO_MANY_ARGS,
	BS_M_MISSING_ARG,
	BS_M_PROCFUNC_DEF_NESTED,
	BS_M_PROCFUNC_DEF,
	BS_M_FORMAL_ARGS_MISMATCH_NUM,
	BS_M_FORMAL_ARG_MISMATCH_TYPE,
	BS_M_TOO_MANY_FORMAL_ARGS,
	BS_M_FUNCDEF_BAD_END,
	BS_M_RETURN_OUTSIDE_FUNC,
	BS_M_RETURN_NO_VALUE,
	BS_M_RETURN_MISSING_VALUE,
	BS_M_LOCAL_OUTSIDE_FUNC,
	BS_M_TOO_MANY_LOCAL_VARS,
	BS_M_CDATA_ONLY_INTEGER,
	BS_M_UNKNOWN_TYPE_READ,
	BS_M_COMPILE_ERROR,
	BS_M_START_PROGRAM,
	BS_M_RUNNING,
	BS_M_PROG_DELETED_YN,
	BS_M_EXIT_IN_DIRECT,
	BS_M_PROG_SAVE_YN,
	BS_M_FINISHED,
	BS_M_ESC_END_EDIT,
	BS_M_OUT_OF_MEMORY,
	BS_M_CANNOT_OPEN,
	BS_M_SOURCE_TOO_LARGE,
	BS_M_NO_PROGRAM_TO_SAVE,
	BS_M_FILE_EXISTS,
	BS_M_SAVE_CANCELED,
	BS_M_CANNOT_WRITE,
	BS_M_ONLY_DIRECT,
	BS_M_INVALID_FNAME,
	BS_M_ZERO_DIVISION,
	BS_M_STACK_UNDERFLOW,
	BS_M_STACK_OVERFLOW,
	BS_M_USER_INTERRUPT,
	BS_M_OUT_OF_MEMORY_STRING,
	BS_M_JUMP_ADDRESS_OUT_OF_RANGE,
	BS_M_OUT_OF_MEMORY_DIM_ALLOC,
	BS_M_DIM_NO_MATCH_RUNTIME,
	BS_M_TOO_MANY_DIM_INIT,
	BS_M_DATA_POS_OUT_OF_RANGE,
	BS_M_DATA_MISMATCH_NUMBER_EXPECTED,
	BS_M_DATA_MISMATCH_STRING_EXPECTED,
	BS_M_CDATA_READ_ONLY_INTEGER,
	BS_M_BAD_DATA_STATEMENT,
	BS_M_PREP_WAIT_ERROR,
};

#endif  /* __TRANSMESSAGE_H__  */


