#  Makefile for BareMetal PiBasic
#  2016.3.13. Toshi Nagata
#  Copyright 2016 Toshi Nagata. All rights reserved.

SRCS := raspi_main.c raspi_framebuffer.c

ARCHFLAGS = -D__RASPBERRY_PI__
PLATFORM = raspi

-include ../Makefile.inc
